{"name": "test_case02[11]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 > 2", "trace": "self = <test_login.TestLogin object at 0x0000017AAB9002E0>, test2 = '11'\n\n    def test_case02(self,test2):\n        print('pytest运行方式-第二')\n>       assert 1 > 2\nE       assert 1 > 2\n\ntest_login.py:50: AssertionError"}, "parameters": [{"name": "test2", "value": "'11'"}], "start": 1700915126070, "stop": 1700915126071, "uuid": "2ea5230d-a21e-4b8b-967d-6e297a23092a", "historyId": "65b2a762a0d290b73a753732c84bf339", "testCaseId": "4e2a30eb37d3ac1c93f82bffa9bd5d4d", "fullName": "testcase.Login.test_login.TestLogin#test_case02", "labels": [{"name": "parentSuite", "value": "testcase.Login"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "liying"}, {"name": "thread", "value": "62208-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.Login.test_login"}]}