{"name": "test_case02[11]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 > 2", "trace": "self = <test_login.TestLogin object at 0x000002C5146B66D0>, test2 = '11'\n\n    def test_case02(self,test2):\n        print('pytest运行方式-第二')\n>       assert 1 > 2\nE       assert 1 > 2\n\ntestcase\\Login\\test_login.py:51: AssertionError"}, "parameters": [{"name": "test2", "value": "'11'"}], "start": 1700915937319, "stop": 1700915937319, "uuid": "7604ec24-358f-4511-9b65-e3c30a50bdc5", "historyId": "65b2a762a0d290b73a753732c84bf339", "testCaseId": "4e2a30eb37d3ac1c93f82bffa9bd5d4d", "fullName": "testcase.Login.test_login.TestLogin#test_case02", "labels": [{"name": "parentSuite", "value": "testcase.Login"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "liying"}, {"name": "thread", "value": "63752-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.Login.test_login"}]}