{"name": "test_case02[22]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 > 2", "trace": "self = <test_login.TestLogin object at 0x000002C5146B67C0>, test2 = '22'\n\n    def test_case02(self,test2):\n        print('pytest运行方式-第二')\n>       assert 1 > 2\nE       assert 1 > 2\n\ntestcase\\Login\\test_login.py:51: AssertionError"}, "parameters": [{"name": "test2", "value": "'22'"}], "start": 1700915937510, "stop": 1700915937510, "uuid": "9f15b264-a19a-4f96-84f8-521e8c47dad8", "historyId": "bee0269268b60207969f32ac5f29f32e", "testCaseId": "4e2a30eb37d3ac1c93f82bffa9bd5d4d", "fullName": "testcase.Login.test_login.TestLogin#test_case02", "labels": [{"name": "parentSuite", "value": "testcase.Login"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "liying"}, {"name": "thread", "value": "63752-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.Login.test_login"}]}